#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 26 19:01:17 2021

@author: zhdanov
"""

import sys
import os
from scipy.io import wavfile
from os.path import dirname, join as pjoin
import matplotlib.pyplot as plt
import numpy as np


def spectr(file_name):                                      # Спектрограмма
    samplerate, data= wavfile.read(file_name)
    length = data.shape[0] / samplerate
    time = np.linspace(0., length, data.shape[0])
# =============================================================================
#     plt.plot(time, (data[:]), label="Plot")
#     plt.xlabel("Time [s]")
#     plt.ylabel("Amplitude")
#     plt.show()
# =============================================================================    
    
    return data

def find_d(your_path):                                      # Поиск дубликатов
                                                                                                               
    fileNames_ = np.array([])                                                      
    f = open('duplicates.txt', 'w')
    
    with os.scandir(your_path) as listOfEntries:        
        for entry in listOfEntries:            
            if entry.is_file():
                fileNames_ = np.append(fileNames_, entry.name)                                                                                                                        
    for i in fileNames_:     
        f.write(i + '\n')                   
        first_data = spectr(pjoin(your_path, i))              
        for j in fileNames_:
            second_data = spectr(pjoin(your_path, j))
            if np.array_equal(first_data, second_data) and (i != j):
                f.write('\t' + 'duplicate: ' + j + '\n')
                                            
    f.close()
    return f.name                                                                   

def main():
    if len (sys.argv) > 1:
        dir_name = sys.argv[1]    
        path = os.path.normpath(pjoin(os.getcwd(), dir_name))
        name = find_d(path)
        print(name, '\n')
        file = open(name, 'r')
        for line in file:
            print(line)
        file.close()

if __name__ == '__main__':
    main()
    
        
                
            